"""attachment added to user model

Revision ID: c67148c0a9c2
Revises: 50700955bcc1
Create Date: 2020-11-10 16:32:50.583779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67148c0a9c2'
down_revision = '50700955bcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('attachment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'attachment')
    # ### end Alembic commands ###
